Idle anims edits
ampreeT/SourceCoop pull request #192
Opened 2024-12-12 20:17 UTC by Alienmario

- Replicate body groups (supported has also been added to modelchooser)
- Uses EF_NODRAW instead of RENDERFX_FADE_FAST
- Moved player reset to UpdateOnRemove hook

( core implementation stay same, gh can't handle diffing indentation )

2024-12-12 20:57 UTC, ampreeT requested changes
Orientation and animations are broken. This happens while running, crouch walking and swimming. This is possibly due to `EF_NODRAW` being applied and not being networked to the players. 

https://github.com/user-attachments/assets/38d9ea9a-292f-4bd3-a2d7-07ceb0574fd3


https://github.com/user-attachments/assets/dc47bfad-5d1e-47f9-98fc-b5d4a5411f54


https://github.com/user-attachments/assets/61f1b107-1666-4c3b-b8b6-ca0e41497c10

2024-12-12 21:06 UTC, Alienmario commented
Guess I'll try RENDER_NONE rendermode or revert to original.

2024-12-12 22:56 UTC, Alienmario commented
Remembered about fade distance. Also not sure if checking the entity properties is necessary before setting them?

2024-12-13 23:11 UTC, ampreeT approved these changes

2024-12-13 23:14 UTC, ampreeT commented
> Remembered about fade distance. Also not sure if checking the entity properties is necessary before setting them?

I wasn't sure either but I tested the new changes that you made and there was no problems that I saw.

2024-12-13 23:20 UTC, merged